### PR TITLE
Move connect button

### LINKED ISSUE #24: Move button on home page

### PR DESCRIPTION
**Pull request by Kaszz**
Closes #24 

Just moved the button.

### CODE REVIEW

**Review by Wylardt — APPROVED** [review]

**Comment by Kechr** [comment]
Do we want the connect button to be next to, or on the other side of, the remove button?

**Review by dottore1 — APPROVED** [review]

**Review by Teyson — CHANGES_REQUESTED** [review]
Place the buttons beside the remove buttons

**Comment by LeaChr96** [comment]
I'm with the others. The button placement is strange.

**Comment by Kaszz** [comment]
The button has been moved

**Review by Teyson — APPROVED** [review]

**Review by LeaChr96 — APPROVED** [review]

**Review by dottore1 — APPROVED** [review]

**Review by Kechr — APPROVED** [review]

**Pull request merged**
