### PR TITLE
5 batch history view

### LINKED ISSUE #5: Batch history view
Create a view with a list of previously produced batches. When a batch is chosen, the view should update so the data from that specific batch is shown. 

Inspiration

### PR DESCRIPTION
**Pull request by Kechr**
This is a big one. closes #5

### CODE REVIEW

**Review by Wylardt — APPROVED** [review]

**Comment by Teyson** [comment]
image

This is how it looks. It's dynamic so that it resizes to fit your screen horizontally

**Comment by Teyson** [comment]
Animation

Gif til de kræsne idioter

**Review by dottore1 — APPROVED** [review]

**Comment by Kaszz** [comment]
ATP was very hard to understand :)

**Comment by Teyson** [comment]
image

ATP is now Ammount to produce

**Review by Kaszz — APPROVED** [review]

**Review by LeaChr96 — APPROVED** [review]
image

**Pull request merged**
